-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: 7ec485352199e02d608198b0206b0675fa84af73
    hooks:
    -   id: flake8
    -   id: trailing-whitespace
    -   id: name-tests-test
-   repo: git://github.com/pre-commit/mirrors-scss-lint
    sha: d7266131da322d6d76a18d6a3659f21025d9ea11
    hooks:
    -   id: scss-lint
-   repo: git@github.com:pre-commit/pre-commit
    sha: 74e878d96a96c137e258d23904f0e99986bf7e2c
    hooks:
    -   id: validate_config
-   repo: git://github.com/pre-commit/mirrors-ruby-lint
    sha: f4b537e0bf868fc6baefcb61288a12b35aac2157
    hooks:
    -   id: ruby-lint
-   repo: git://github.com/pre-commit/mirrors-jshint
    sha: 8e7fa9caad6f7b2aae8d2c7b64f457611416192b
    hooks:
    -   id: jshint
